# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-23 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('advertiser', 'Advertiser'), ('moderator', 'Moderator'), ('admin', 'Admin')], default='advertiser', max_length=20),
        ),
    ]
