# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-24 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20171123_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='recovery_code',
            field=models.CharField(blank=True, db_index=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='recovery_hash',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='activation_code',
            field=models.CharField(blank=True, db_index=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='activation_code_hash',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
    ]
