# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-04 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20171205_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='business',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
