# Generated by Django 2.0.1 on 2018-04-03 18:14

from django.db import migrations


def forwards_func(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Group = apps.get_model("auth", "Group")
    db_alias = schema_editor.connection.alias

    base_group, _ = Group.objects.using(db_alias).get_or_create(
        name='base',
    )
    advertisers_group, _ = Group.objects.using(db_alias).get_or_create(
        name='advertisers',
    )
    Group.objects.using(db_alias).get_or_create(
        name='moderators',
    )
    admin_group, _ = Group.objects.using(db_alias).get_or_create(
        name='admins',
    )
    bots_group, _ = Group.objects.using(db_alias).get_or_create(
        name='bots',
    )
    system_group, _ = Group.objects.using(db_alias).get_or_create(
        name='system',
    )

    users = User.objects.all()
    for user in users:
        if user.is_superuser:
            user.groups.add(admin_group)
        user.groups.add(advertisers_group, base_group)
        user.save()

    condusterBot, _ = User.objects.using(db_alias).get_or_create(
        username='condusterBot',
        password='pbkdf2_sha256$100000$vf3EOzOAFrGZ$jckb1TJtPL4OmwWmhnrDnJi9RaFGoaBShHt175l7QM4='
    )
    condusterBot.groups.add(bots_group)
    condusterBot.save()


class Migration(migrations.Migration):
    dependencies = [
        ('profiles', '0007_auto_20180226_1628'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
