# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flatpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='XFlatPage',
            fields=[
                ('flatpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flatpages.FlatPage')),
                ('content_ru', models.TextField(blank=True, verbose_name='content_ru')),
            ],
            bases=('flatpages.flatpage',),
        ),
    ]
