# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xflatpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xflatpage',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='title_ru'),
        ),
    ]
