# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-25 05:08
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessionStorage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_agent_string', models.CharField(blank=True, max_length=2056, null=True)),
                ('os_family', models.CharField(blank=True, max_length=52, null=True)),
                ('os_version', models.CharField(blank=True, max_length=52, null=True)),
                ('browser_family', models.CharField(blank=True, max_length=52, null=True)),
                ('browser_version', models.CharField(blank=True, max_length=52, null=True)),
                ('device_family', models.CharField(blank=True, max_length=52, null=True)),
                ('device_brand', models.CharField(blank=True, max_length=52, null=True)),
                ('device_model', models.CharField(blank=True, max_length=52, null=True)),
                ('cookie_enabled', models.BooleanField(default=False)),
                ('current_language', models.CharField(blank=True, max_length=20, null=True)),
                ('languages', models.CharField(blank=True, max_length=100, null=True)),
                ('java_enabled', models.BooleanField(default=False)),
                ('online', models.BooleanField(default=False)),
                ('plugin_list', models.CharField(blank=True, max_length=3000, null=True)),
                ('timezone_offset', models.IntegerField(blank=True, null=True)),
                ('screen_height', models.IntegerField(blank=True, null=True)),
                ('screen_width', models.IntegerField(blank=True, null=True)),
                ('screen_color_depth', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=512, null=True)),
                ('referrer', models.CharField(blank=True, max_length=512, null=True)),
                ('page_title', models.TextField(blank=True, null=True)),
                ('form_has_hidden_fields', models.BooleanField(default=False)),
            ],
        ),
    ]
