# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-05 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_auto_20171105_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='url',
        ),
        migrations.AddField(
            model_name='project',
            name='tag',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
