# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-27 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0005_auto_20171127_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='pixel',
            name='title',
            field=models.CharField(default='Форма', max_length=128),
            preserve_default=False,
        ),
    ]
