# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-11 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0007_auto_20171128_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_started', models.DateTimeField()),
                ('last_event_time', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('pixel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='collector.Pixel')),
            ],
        ),
    ]
