# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-19 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0009_auto_20171214_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionstorage',
            name='available_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionstorage',
            name='available_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionstorage',
            name='domain',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='sessionstorage',
            name='form_disabled_fields',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionstorage',
            name='form_hidden_fields',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionstorage',
            name='form_total_fields',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionstorage',
            name='get_params',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='sessionstorage',
            name='ip_addr',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionstorage',
            name='page_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionstorage',
            name='viewport_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionstorage',
            name='viewport_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessionstorage',
            name='page_title',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
