# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-20 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0010_auto_20171219_0255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='sessionstorage',
            name='ad_block',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessionstorage',
            name='canvas_byte_array',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionstorage',
            name='has_idb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessionstorage',
            name='has_ls',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessionstorage',
            name='has_odb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessionstorage',
            name='has_ss',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessionstorage',
            name='orientation',
            field=models.CharField(blank=True, choices=[('landscape', 'landscape'), ('portrait', 'portrait')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sessionstorage',
            name='webgl_vendor',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='sessionstorage',
            name='fonts',
            field=models.ManyToManyField(blank=True, to='collector.Font'),
        ),
    ]
