# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-21 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    db_alias = schema_editor.connection.alias
    Session = apps.get_model("collector", "SessionStorage")
    sessions = Session.objects.using(db_alias).all()
    Pixel = apps.get_model("collector", "Pixel")
    pixel = None
    for session in sessions:
        if not pixel:
            pixel = Pixel.objects.using(db_alias)[0]
        session.pixel = pixel
        session.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0012_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionstorage',
            name='pixel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collector.Pixel'),
            preserve_default=False,
        ),
        migrations.RunPython(forwards_func, reverse_func),
        migrations.AlterField(
            model_name='sessionstorage',
            name='pixel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.Pixel'),
            preserve_default=False,
        ),
    ]
