# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-26 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0013_sessionstorage_pixel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='even_type',
            new_name='event_type',
        ),
        migrations.AlterField(
            model_name='event',
            name='field_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='field_parent',
            field=models.ForeignKey(blank=True, help_text='previous filled field', null=True, on_delete=django.db.models.deletion.CASCADE, to='collector.Event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='field_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='finished',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='hash_data',
            field=models.CharField(blank=True, help_text='entered data hash', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='started',
            field=models.DateTimeField(db_index=True),
        ),
    ]
