# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-27 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0014_auto_20171226_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='pixel',
            name='save_client_data',
            field=models.BooleanField(default=True),
        ),
    ]
