# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-05 01:23
from __future__ import unicode_literals
import os

from django.conf import settings
from django.db import migrations
from pyexcel_xlsx import get_data


def fill_refs(apps, schema_editor):
	data = get_data("{0}/{1}.xlsx".format(os.path.join(settings.BASE_DIR, 'refs_data'),
		'browsers'))
	data = data['Отчет']

	BrowserFamily = apps.get_model('collector', 'BrowserFamily')
	BrowserVersion = apps.get_model('collector', 'BrowserVersion')

	other = BrowserFamily.objects.create(name="other")
	BrowserVersion.objects.create(version="other", family=other)

	for b in data[1:]:
		bf, created = BrowserFamily.objects.get_or_create(name=b[0].lower())
		BrowserVersion.objects.create(family=bf, version=b[1].lower())




class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0018_browserfamily_browserversion'),
    ]

    operations = [
		migrations.RunPython(fill_refs),
    ]
