# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-05 01:46
from __future__ import unicode_literals
import os

from django.conf import settings
from django.db import migrations
from pyexcel_xlsx import get_data


def fill_refs(apps, schema_editor):
	data = get_data("{0}/{1}.xlsx".format(os.path.join(settings.BASE_DIR, 'refs_data'),
		'os'))
	data = data['Отчет']

	OSFamily = apps.get_model('collector', 'OSFamily')
	OS = apps.get_model('collector', 'OS')

	other = OSFamily.objects.create(name="other")
	OS.objects.create(name="other", family=other)

	for o in data[3:]:
		of, created = OSFamily.objects.get_or_create(name=o[0].lower())
		OS.objects.create(family=of, name=o[1].lower())


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0020_auto_20180105_0146'),
    ]

    operations = [
		migrations.RunPython(fill_refs),
    ]
