# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-05 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0021_auto_20180105_0146'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenResolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveSmallIntegerField()),
                ('height', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
