# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-09 05:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0023_auto_20180105_0206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionstorage',
            name='browser_family',
        ),
        migrations.RemoveField(
            model_name='sessionstorage',
            name='browser_version',
        ),
        migrations.RemoveField(
            model_name='sessionstorage',
            name='device_brand',
        ),
        migrations.RemoveField(
            model_name='sessionstorage',
            name='device_family',
        ),
        migrations.RemoveField(
            model_name='sessionstorage',
            name='device_model',
        ),
        migrations.RemoveField(
            model_name='sessionstorage',
            name='os_family',
        ),
        migrations.RemoveField(
            model_name='sessionstorage',
            name='screen_height',
        ),
        migrations.RemoveField(
            model_name='sessionstorage',
            name='screen_width',
        ),
        migrations.AddField(
            model_name='sessionstorage',
            name='browser',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='collector.BrowserVersion'),
        ),
        migrations.AddField(
            model_name='sessionstorage',
            name='device',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='collector.Device'),
        ),
        migrations.AddField(
            model_name='sessionstorage',
            name='screen',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='collector.ScreenResolution'),
        ),
        migrations.AlterField(
            model_name='sessionstorage',
            name='os_version',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='collector.OS'),
        ),
    ]
