# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-11 03:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0024_auto_20180109_0536'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('name_ru', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=10, null=True)),
                ('region_ru', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=12, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='sessionstorage',
            name='geo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='collector.City'),
        ),
    ]
