# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-17 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0025_auto_20180111_0350'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_name', models.CharField(max_length=128)),
                ('html_tag', models.CharField(max_length=30)),
                ('html_attr_name', models.CharField(max_length=50)),
                ('html_attr_value', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('pixel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields_mapping', to='collector.Pixel')),
            ],
        ),
        migrations.CreateModel(
            name='LeadField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50)),
                ('field_hash', models.CharField(max_length=100)),
                ('field_data', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ('-session_started',)},
        ),
        migrations.AddField(
            model_name='event',
            name='field_tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sessionstorage',
            name='submitted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='collector.SessionStorage'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='session_started',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddField(
            model_name='leadfield',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='collector.Lead'),
        ),
        migrations.AlterIndexTogether(
            name='leadfield',
            index_together=set([('field_name', 'field_hash')]),
        ),
    ]
