# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-17 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0026_auto_20180117_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldmapping',
            name='required',
            field=models.BooleanField(default=True),
        ),
    ]
