# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-19 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0027_fieldmapping_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='pixel',
            name='lead_type',
            field=models.CharField(blank=True, choices=[
                ("mortgage", "ипотека"),
                ("cash loan", "кредит наличными"),
                ("credit card", "кредитная карта"),
                ("business credit", "кредит на бизнес"),
                ("micro loan", "микро-заём"),
            ], max_length=100, null=True),
        ),
    ]
