# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-24 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0028_pixel_lead_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='ip_addr',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='subnet',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
