# Generated by Django 2.0.1 on 2018-01-31 14:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0030_fill_test_leads'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpStat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('ip', models.GenericIPAddressField(db_index=True)),
                ('cl_type', models.CharField(blank=True, help_text='Client type', max_length=255, null=True)),
                ('s_cnt', models.IntegerField(default=0, help_text='Total amount of sessions')),
                ('s_time', models.DurationField(default=datetime.timedelta(0), help_text='Total duration of sessions')),
                ('s0_cnt', models.IntegerField(default=0, help_text='Total amount of unfinished sessions')),
                ('s_cnt30', models.IntegerField(default=0, help_text='Amount of sessions in last 30 days')),
                ('s_time30', models.DurationField(default=datetime.timedelta(0), help_text='Duration of sessions in last 30 days')),
                ('s0_cnt30', models.IntegerField(default=0, help_text='Amount of unfinished sessions in last 30 days')),
                ('s_cnt10', models.IntegerField(default=0, help_text='Amount of sessions in last 10 days')),
                ('s_time10', models.DurationField(default=datetime.timedelta(0), help_text='Duration of sessions in last 10 days')),
                ('s0_cnt10', models.IntegerField(default=0, help_text='Amount of unfinished sessions in last 10 days')),
                ('s_cnt3', models.IntegerField(default=0, help_text='Amount of sessions in last 3 days')),
                ('s_time3', models.DurationField(default=datetime.timedelta(0), help_text='Duration of sessions in last 3 days')),
                ('s0_cnt3', models.IntegerField(default=0, help_text='Amount of unfinished sessions in last 3 days')),
                ('s_beg30', models.TimeField(default=datetime.time(0, 0), help_text='Avg time session start in last 30')),
                ('s_beg10', models.TimeField(default=datetime.time(0, 0), help_text='Avg time session start in last 10')),
                ('s_beg3', models.TimeField(default=datetime.time(0, 0), help_text='Avg time session start in last 3')),
                ('ip_state', models.CharField(blank=True, choices=[('low risk', 'low risk'), ('middle risk', 'middle risk'), ('high risk', 'high risk')], max_length=10, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('index', models.CharField(blank=True, help_text='Postal code', max_length=12, null=True)),
                ('cnt_dev30', models.IntegerField(default=0, help_text='Amount of devices in last 30 days')),
                ('cnt_dev10', models.IntegerField(default=0, help_text='Amount of devices in last 10 days')),
                ('cnt_dev3', models.IntegerField(default=0, help_text='Amount of devices in last 3 days')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='collector.City')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asn', models.CharField(db_index=True, max_length=255)),
                ('asn_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={},
        ),
        migrations.AddField(
            model_name='lead',
            name='geo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='collector.City'),
        ),
        migrations.AlterField(
            model_name='browserversion',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collector.BrowserFamily'),
        ),
        migrations.AlterField(
            model_name='device',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collector.DeviceBrand'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collector.DeviceType'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='last_event_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='pixel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='collector.Pixel'),
        ),
        migrations.AlterField(
            model_name='os',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collector.OSFamily'),
        ),
        migrations.AlterField(
            model_name='sessionstorage',
            name='browser',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='collector.BrowserVersion'),
        ),
        migrations.AlterField(
            model_name='sessionstorage',
            name='device',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='collector.Device'),
        ),
        migrations.AlterField(
            model_name='sessionstorage',
            name='geo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='collector.City'),
        ),
        migrations.AlterField(
            model_name='sessionstorage',
            name='os_version',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='collector.OS'),
        ),
        migrations.AlterField(
            model_name='sessionstorage',
            name='pixel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collector.Pixel'),
        ),
        migrations.AlterField(
            model_name='sessionstorage',
            name='screen',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='collector.ScreenResolution'),
        ),
        migrations.AddField(
            model_name='ipstat',
            name='provider',
            field=models.ForeignKey(blank=True, help_text='Inet provider', null=True, on_delete=django.db.models.deletion.PROTECT, to='collector.Provider'),
        ),
        migrations.AddField(
            model_name='lead',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='collector.Provider'),
        ),
        migrations.AddField(
            model_name='sessionstorage',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='collector.Provider'),
        ),
    ]
