# Generated by Django 2.0.1 on 2018-02-05 08:11
from __future__ import unicode_literals

from django.db import migrations

def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    pass

def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0031_auto_20180131_1448'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
