# Generated by Django 2.0.1 on 2018-02-05 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0032_fill_test_leads'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadOpenstat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('campaign', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('ad', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openstat', to='collector.Lead')),
            ],
        ),
        migrations.CreateModel(
            name='LeadUtm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utm_source', models.CharField(db_index=True, max_length=255)),
                ('utm_medium', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('utm_campaign', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('utm_term', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('utm_content', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utm', to='collector.Lead')),
            ],
        ),
    ]
