# Generated by Django 2.0.1 on 2018-02-06 16:04

from django.db import migrations


def forwards_func(apps, schema_editor):
    pass

def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0033_leadopenstat_leadutm'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
