# Generated by Django 2.0.1 on 2018-03-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0035_auto_20180226_1110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'cities'},
        ),
        migrations.AddField(
            model_name='lead',
            name='metrik_lead_duration',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
