# Generated by Django 2.0.1 on 2018-03-13 14:26

from django.db import migrations


def forwards_func(apps, schema_editor):
    pass


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('collector', '0037_lead_metrik_lead_salecount'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
