# Generated by Django 2.0.1 on 2018-03-15 14:02

from django.db import migrations
from django.contrib.auth.hashers import make_password

from collector.management.commands.fill_test_leads import fill_test_leads


def forwards_func(apps, schema_editor):
    pass


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('collector', '0039_auto_20180315_1359'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
