# Generated by Django 2.0.1 on 2018-03-20 10:28


from django.db import migrations

def forwards_func(apps, schema_editor):
    pass

def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('collector', '0041_auto_20180315_1643'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
