# Generated by Django 2.0.1 on 2018-03-21 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0042_fill_test_leads'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='os',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collector.OSFamily'),
        ),
        migrations.AddField(
            model_name='lead',
            name='traffic_channel',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='collector.TrafficChannel'),
        ),
    ]
