# Generated by Django 2.0.1 on 2018-03-28 11:27

from django.db import migrations, models

def forwards_func(apps, schema_editor):
    OSGroup = apps.get_model("collector", "OSGroup")
    group_names = ('Google Android', 'iOS', 'Tizen', 'BlackBerry OS', 'SymbianOS')
    db_alias = schema_editor.connection.alias
    OSGroup.objects.using(db_alias).filter(name__in=group_names).update(is_mobile=True)



def reverse_func(apps, schema_editor):
    pass



class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0045_fill_test_leads'),
    ]

    operations = [
        migrations.AddField(
            model_name='osgroup',
            name='is_mobile',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.RunPython(forwards_func, reverse_func),
        migrations.AlterField(
            model_name='devicetype',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Phone'), (2, 'Tablet'), (3, 'Desktop')]),
        ),
    ]
