# Generated by Django 2.0.1 on 2018-02-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='processed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
