# Generated by Django 2.0.1 on 2018-02-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0035_auto_20180226_1110'),
        ('audit', '0002_auto_20180222_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicationRequiredFieldSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fields', models.ManyToManyField(related_name='duplication_required_fieldsets', to='collector.Field')),
            ],
        ),
    ]
